- add action press to move page manage call
brekekesoftware/brekekephone pull request #64
Opened 2021-12-23 16:13 UTC by tatthangcntt

It does not display multiple incoming calls after brekeke phone try to pickup the call just canceled.
**Issue**:
1. Make 3 incoming calls to brekeke phone following oders: 101, 102, 103
2. the last one 103 rings and displays on top of the brekeke phone's screen.
3. 103 cancels and the brekeke phone try to pickup the call at the same time.
=> The call is disconnected, But it shows a screen like
current list -> 102 is ringing
background list -> 101 is riniging
4. The brekeke phone try to select arrow button to move to main screen of the phone.
=> Actual: Now, it just shows only one call (102) on Call bar, and cannot move change back to background list anymore.
Expected: It can change back the screen to see background list.
5. Press Disconnected, 
=> Actual: the call 102 is disconnected. It does not display remaing call (101), while 101 keep dialing status.

2022-01-12 03:32 UTC, namnm commented
Trong code hiện tại mới fix dc 4. Còn cái 5. chưa fix

2022-01-12 03:34 UTC, namnm requested changes

2022-01-12 03:34 UTC, namnm commented on src/components/CallNotify.tsx
>        <View style={css.Notify}>
Cho TouchableOpacity ra ngoài này dc k để vùng touch nó rộng ra?

2022-01-17 17:26 UTC, tatthangcntt commented
> Trong code hiện tại mới fix dc 4. Còn cái 5. chưa fix

Hiện tại chưa tái hiện được cái số 5!

2022-01-17 17:26 UTC, tatthangcntt commented on src/components/CallNotify.tsx
>        <View style={css.Notify}>
Ok!

2022-01-25 17:55 UTC, merged